name: build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: genesys-ui/gh-workflows/.github/workflows/cache@main
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
