name: build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: genesys-ui/gh-workflows/actions/setup-node@main
      - uses: genesys-ui/gh-workflows/actions/cache@main
      - run: pnpm install
      - run: pnpm build
