name: mutation-testing
on:
  workflow_call:

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: genesys-ui/gh-workflows/.github/workflows/cache
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - run: mkdir mutation-test-results
      - run: pnpm run stryker
      - run: |
          cd mutation-test-results
          cp /home/runner/work/genesys-icons/genesys-icons/reports/mutation/mutation.html stryker-report.html
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: mutation-test-results
          path: mutation-test-results
