name: mutation-testing
on:
  workflow_call:

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: genesys-ui/gh-workflows/actions/setup-node@main
      - uses: genesys-ui/gh-workflows/actions/cache@main
      - run: npx stryker run
      - uses: actions/upload-artifact@v4
        with:
          name: mutation-test-results
          path: reports/mutation
