name: release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry:
        required: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: genesys-ui/gh-workflows/actions/setup-node@main
      - uses: genesys-ui/gh-workflows/actions/cache@main
      - run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Publish ${{ inputs.version }}${{ inputs.dry && ' (--dry-run)' || '' }}
        run: npx release-it ${{ inputs.version != 'auto' && inputs.version || '' }}${{ inputs.dry && ' --dry-run' || '' }} --ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
