name: release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry:
        required: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: ./.github/workflows/cache
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - run: |
          git config --global user.name 'Genesys UI GitHub Action'
          git config --global user.email 'ci@genesys-ui.dev'
      - name: Publish ${{ inputs.version }}${{ inputs.dry == 'true' && ' (--dry-run)' || '' }}
        run: pnpm run release --ci -- ${{ inputs.version != 'auto' && inputs.version || '' }}${{ inputs.dry == 'true' && ' --dry-run' || '' }}
