name: test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: genesys-ui/gh-workflows/actions/setup-node@main
      - uses: genesys-ui/gh-workflows/actions/cache@main
      - run: pnpm lint
      - run: pnpm test -- --coverage
