name: test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: ./.github/workflows/cache
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - run: pnpm lint
      - run: pnpm test
