name: test
on:
  workflow_call:

jobs:
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: ./.github/workflows/cache
      - run: pnpm lint
      - run: pnpm test
